package:
    name: gorgon-legacy
    version: 2.3

build:
    number: 0

source:
    git_url: https://github.com/GorgonCryoEM/Gorgon.git
    git_tag: appveyor      # [win]
    git_tag: non-appveyor  # [not win]

requirements:
    build:
        - cmake >=3.4
        - python 2.7.*
        - boost         # [not win]
        - boost-gorgon  # [win]
        - fftw
        - freeglut  # [not osx]
        - setuptools
    run:
        - python 2.7.*
        - boost         # [not win]
        - boost-gorgon  # [win]
        - fftw
        - freeglut  # [not osx]
        - pyqt
        - pyopengl
        - vs2015_runtime  # [win]

about:
  summary: Gorgon, an interactive molecular modeling system
