travis:
  secure:
    BINSTAR_TOKEN: AaT9BFfWeA7DXobnTtW58SkD75glK4WUJAADot0pdu/2oSIuHmKZeV6vlC3dbby1Hb60cRFFf7m/oO/Kou84ifP3gFKhO0U/taHWySkbl0yF5xkEDzVkLkqybdosH+SjdaakIQDfkwdfkhvp2Tv3Q88s0dD42+65+KW+7rg2gq5GfxGpRxby0Fm9xUP11l6B6E7srvrHEVacs6WI96dDA27/1yNj+Hjm+Lc1ZI6LvPOPH96IHkYzZk86SPf0bzEzBt1nxsLeDyZO+EZ6DGgAlJqZ4TBaeaufmF4kthPp6sOHMUjND+MuRhD1WwFCspv/rmYlt1z+h8fC5Dni4z1PLrbcCQZaiP7ksj1DQ+zyel6CMz2/FSEllQ73983Ek2zZ0RC23lM/XuihOfCDT/XNfRWPkx4UYm5tQq061mFaMgg7ZCosURfq3n8nmjk+CMz0RQ+GLYE4aiFYaZ9gqooliZZP4wUuqijwmBUDhqSVftTSNOSJiTdUkw8Z3dqcahxx64nJw1H521oGLPmWSeIAKX83dMq5lA15a7BiDkqGpBGhkbMMXAo+Ruvlv6tbJut56mwPw2uCInYG1F0ci20qzMDRlXlq2qpXuyXCFSG2aaA3J8CqyrPIX2Lg2/S4KjckCzXA//+/stRkozAk7ZHSJdJ1YsQ8qI81svtTy3RtCjM=
appveyor:
  secure:
    BINSTAR_TOKEN: 4ef5IUakGqqw7GSfuIp93Q4MdAC1VnweE1kFVAOUs6ThPDQWBqNpGaq6ZuEbX1FL

channels:
  sources: [gorgoncryoem/label/dependency, conda-forge]
  targets:
    - [gorgoncryoem, main]

github:
  user_or_org: GorgonCryoEM
  repo_name: gorgon-legacy-feedstock
